services:
  - type: web
    name: adega-system
    runtime: node
    repo: https://github.com/yanlt32/sistemadega2.0
    plan: free
    region: oregon
    buildCommand: cd backend && npm install --build-from-source
    startCommand: cd backend && npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production